---
version: '3.9'
services:
  develop-image:
    image: dandelion000/ubuntu:develop
    build: 
      context: dockerfiles
      dockerfile: Dockerfile
      labels:
        - "MAINTAINER=dandelion000"
      network: host

  develop:
    image: dandelion000/ubuntu:develop
    volumes:
      - "./:/root/cpp_learn"
    command: [ "/usr/bin/tail", "-f", "/dev/null" ]
    working_dir: /root/cpp_learn
    privileged: true
    networks:
      - "test"

networks:
  test: {}