cc_binary(
  name = "select_test",
  srcs = ["select_test.cc"],
  deps = [
    "@com_github_google_glog//:glog",
  ],
)

cc_binary(
  name = "poll_test",
  srcs = ["poll_test.cc"],
  deps = [
    "@com_github_google_glog//:glog",
  ],
)

# mac os 不支持
#cc_binary(
#  name = "epoll_test",
#  srcs = ["epoll_test.cc"],
#)