cc_test(
  name = "murmurhash_test",
  srcs = ["murmurhash_test.cc"],
  deps = [
    "//cpp/datastructure/hash:hash",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_test(
  name = "crc32_test",
  srcs = ["crc32_test.cc"],
  deps = [
    "//cpp/datastructure/hash:hash",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_test(
  name = "md5_test",
  srcs = ["md5_test.cc"],
  deps = [
    "//cpp/datastructure/hash:hash",
    "@com_google_googletest//:gtest_main",
  ],
)