#cc_test(
#  name = "ringbuffer_test",
#  srcs = ["ringbuffer_test.cc"],
#  deps = [
#    "//cpp/datastructure/queue:queue",
#    "@com_google_googletest//:gtest_main",
#  ]
#)

#cc_binary(
#  name = "ringbuffer_benchmark",
#  srcs = [
#    "ringbuffer_benchmark.cc",
#  ],
#  deps = [
#    "//cpp/datastructure/queue:queue",
#    "@com_github_google_benchmark//:benchmark",
#  ]
#)