# mac m1 不支持 intel 指令集
#cc_library(
#  name = "simd_sum",
#  hdrs = ["simd_sum.h"],
#  visibility = ["//visibility:public"],
#  deps = [
#    "@com_github_google_glog//:glog",
#  ],
#)

cc_library(
  name = "macros",
  hdrs = ["macros.h"],
  visibility = ["//visibility:public"],
)

cc_library(
  name = "timer",
  hdrs = ["timer.h"],
  visibility = ["//visibility:public"],
)