cc_binary(
  name = "class_test",
  srcs = ["class_test.cc"],
)

cc_binary(
  name = "class_inheritance_test",
  srcs = ["class_inheritance_test.cc"],
)

cc_binary(
  name = "condition_variable_test",
  srcs = ["condition_variable_test.cc"],
  linkopts = ["-lpthread"],
)

cc_binary(
  name = "template_test",
  srcs = ["template_test.cc"],
)

cc_binary(
  name = "thread_test",
  srcs = ["thread_test.cc"],
  linkopts = [
    "-lpthread",
  ]
)

cc_binary(
  name = "traits_test",
  srcs = ["traits_test.cc"],
  linkopts = ["-lpthread"],
)