cc_library(
  name = "cpp_library",
  srcs = glob(["*.cc"]),
  hdrs = glob(["*.h"]),
  visibility = ["//visibility:public"],
)

cc_binary(
  name = "thread_main",
  srcs = [
    "thread.cc",
  ]
)

cc_binary(
  name = "templates",
  srcs = [
    "templates.cc",
  ]
)