cc_binary(
  name = "class_test",
  srcs = ["class_test.cc"],
)

cc_binary(
  name = "condition_variable_test",
  srcs = ["condition_variable_test.cc"],
)

cc_binary(
  name = "template_test",
  srcs = ["template_test.cc"],
)

cc_binary(
  name = "thread_test",
  srcs = ["thread_test.cc"],
)