cc_binary(
  name = "pipe_test",
  srcs = ["pipe_test.cc"],
  deps = [
    "@com_github_google_glog//:glog",
  ],
)

cc_binary(
  name = "popen_test",
  srcs = ["popen_test.cc"],
)

cc_binary(
  name = "fifo_test",
  srcs = ["fifo_test.cc"],
)