cc_test(
  name = "singleton_test",
  srcs = [
    "singleton_test.cc",
  ],
  deps = [
    "//cpp/design_patterns/creational_patterns:creational_patterns",
    "@com_google_googletest//:gtest_main",
  ],
)