cc_binary(
  name = "client",
  srcs = ["client.cc"],
  deps = [
    "@com_github_google_glog//:glog",
  ],
)

cc_binary(
  name = "server",
  srcs = ["server.cc"],
  deps = [
     "@com_github_google_glog//:glog",
  ],
)