cc_library(
  name = "simd_sum",
  srcs = ["simd_sum.cc"],
  hdrs = ["simd_sum.h"],
  visibility = ["//visibility:public"],
  copts = ["-ftemplate-depth=65535"],
  deps = [
    "@com_github_google_glog//:glog",
  ],
)