cc_binary(
  name = "pipe_test",
  srcs = ["pipe_test.cc"],
  deps = [
    "@com_github_google_glog//:glog",
  ],
)

cc_binary(
  name = "popen_test",
  srcs = ["popen_test.cc"],
)

cc_binary(
  name = "fifo_test",
  srcs = ["fifo_test.cc"],
)

cc_binary(
  name = "sendfile_test",
  srcs = ["sendfile_test.cc"],
)

cc_binary(
  name = "mmap_test",
  srcs = ["mmap_test.cc"],
)

cc_binary(
  name = "splice_test",
  srcs = ["splice_test.cc"],
)

cc_binary(
  name = "change_user_test",
  srcs = ["change_user_test.cc"],
)

cc_binary(
  name = "daemon_test",
  srcs = ["daemon_test.cc"],
)